# Generated by Django 6.0.3 on 2026-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('volume_ml', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alcohol_percent', models.FloatField()),
                ('is_in_stock', models.BooleanField(default=True)),
                ('release_year', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
